// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdWVwZUNXELmiOaDvJqFoKE2G4-GDDz-k',
    appId: '1:165273895960:web:78c4d344e249c4e3e9ef6d',
    messagingSenderId: '165273895960',
    projectId: 'the-kids-app-prod',
    authDomain: 'the-kids-app-prod.firebaseapp.com',
    storageBucket: 'the-kids-app-prod.firebasestorage.app',
    measurementId: 'G-L4WCS9505W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQHcGFndg_q8u-8BHdQ8bgvvjBRRD08_I',
    appId: '1:165273895960:android:c31018b15817778be9ef6d',
    messagingSenderId: '165273895960',
    projectId: 'the-kids-app-prod',
    storageBucket: 'the-kids-app-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPDxeCsdrtsyYwHx6e90NCCdBLRBk63f0',
    appId: '1:165273895960:ios:6e14f8ffaa3ae737e9ef6d',
    messagingSenderId: '165273895960',
    projectId: 'the-kids-app-prod',
    storageBucket: 'the-kids-app-prod.firebasestorage.app',
    iosBundleId: 'space.prtlab.theKidsApp',
  );

}