// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQ8_Va8hRrhe42t35tVxOhnOzdVgOYfpM',
    appId: '1:508679998975:web:74eeee84e03430cfce6bca',
    messagingSenderId: '508679998975',
    projectId: 'the-kids-app-dev',
    authDomain: 'the-kids-app-dev.firebaseapp.com',
    storageBucket: 'the-kids-app-dev.firebasestorage.app',
    measurementId: 'G-2DH8W0LRBF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDT15btam139c0m8HX2wLiohAFMnUJE2w',
    appId: '1:508679998975:android:056f21ce06ff2690ce6bca',
    messagingSenderId: '508679998975',
    projectId: 'the-kids-app-dev',
    storageBucket: 'the-kids-app-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiGSUwdgqV4ZqrX5L93bt5L_VI7tO-b0s',
    appId: '1:508679998975:ios:00b8e200f5b2ef41ce6bca',
    messagingSenderId: '508679998975',
    projectId: 'the-kids-app-dev',
    storageBucket: 'the-kids-app-dev.firebasestorage.app',
    iosBundleId: 'space.prtlab.theKidsApp.dev',
  );

}