// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'src/data/dtos/exercise/exercise_store_dto.dart';
import 'src/data/dtos/learned_word/learned_word_dto.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 725523412170617825),
    name: 'LearnedWordDto',
    lastPropertyId: const obx_int.IdUid(5, 2670898210283975493),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1606731236105225511),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7874128429129372026),
        name: 'word',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1313751514869386558),
        name: 'category',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4531644472347452069),
        name: 'seenCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2670898210283975493),
        name: 'exerciseCount',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 5221871103982835752),
    name: 'ExerciseStoreDto',
    lastPropertyId: const obx_int.IdUid(3, 8590352075993328948),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3745134515628992499),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6468066045194937601),
        name: 'exerciseType',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8590352075993328948),
        name: 'jsonContent',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(2, 5221871103982835752),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    LearnedWordDto: obx_int.EntityDefinition<LearnedWordDto>(
      model: _entities[0],
      toOneRelations: (LearnedWordDto object) => [],
      toManyRelations: (LearnedWordDto object) => {},
      getId: (LearnedWordDto object) => object.id,
      setId: (LearnedWordDto object, int id) {
        object.id = id;
      },
      objectToFB: (LearnedWordDto object, fb.Builder fbb) {
        final wordOffset = fbb.writeString(object.word);
        final categoryOffset = fbb.writeString(object.category);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, wordOffset);
        fbb.addOffset(2, categoryOffset);
        fbb.addInt64(3, object.seenCount);
        fbb.addInt64(4, object.exerciseCount);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final wordParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final categoryParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final seenCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final exerciseCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final object = LearnedWordDto(
          id: idParam,
          word: wordParam,
          category: categoryParam,
          seenCount: seenCountParam,
          exerciseCount: exerciseCountParam,
        );

        return object;
      },
    ),
    ExerciseStoreDto: obx_int.EntityDefinition<ExerciseStoreDto>(
      model: _entities[1],
      toOneRelations: (ExerciseStoreDto object) => [],
      toManyRelations: (ExerciseStoreDto object) => {},
      getId: (ExerciseStoreDto object) => object.id,
      setId: (ExerciseStoreDto object, int id) {
        object.id = id;
      },
      objectToFB: (ExerciseStoreDto object, fb.Builder fbb) {
        final exerciseTypeOffset = fbb.writeString(object.exerciseType);
        final jsonContentOffset = fbb.writeString(object.jsonContent);
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, exerciseTypeOffset);
        fbb.addOffset(2, jsonContentOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final exerciseTypeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final jsonContentParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final object = ExerciseStoreDto(
          id: idParam,
          exerciseType: exerciseTypeParam,
          jsonContent: jsonContentParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [LearnedWordDto] entity fields to define ObjectBox queries.
class LearnedWordDto_ {
  /// See [LearnedWordDto.id].
  static final id = obx.QueryIntegerProperty<LearnedWordDto>(
    _entities[0].properties[0],
  );

  /// See [LearnedWordDto.word].
  static final word = obx.QueryStringProperty<LearnedWordDto>(
    _entities[0].properties[1],
  );

  /// See [LearnedWordDto.category].
  static final category = obx.QueryStringProperty<LearnedWordDto>(
    _entities[0].properties[2],
  );

  /// See [LearnedWordDto.seenCount].
  static final seenCount = obx.QueryIntegerProperty<LearnedWordDto>(
    _entities[0].properties[3],
  );

  /// See [LearnedWordDto.exerciseCount].
  static final exerciseCount = obx.QueryIntegerProperty<LearnedWordDto>(
    _entities[0].properties[4],
  );
}

/// [ExerciseStoreDto] entity fields to define ObjectBox queries.
class ExerciseStoreDto_ {
  /// See [ExerciseStoreDto.id].
  static final id = obx.QueryIntegerProperty<ExerciseStoreDto>(
    _entities[1].properties[0],
  );

  /// See [ExerciseStoreDto.exerciseType].
  static final exerciseType = obx.QueryStringProperty<ExerciseStoreDto>(
    _entities[1].properties[1],
  );

  /// See [ExerciseStoreDto.jsonContent].
  static final jsonContent = obx.QueryStringProperty<ExerciseStoreDto>(
    _entities[1].properties[2],
  );
}
